# Generated by Django 3.2 on 2022-06-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_adding_fields_for_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='file_path',
        ),
    ]
