# Generated by Django 3.2 on 2022-06-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_adding_null_true_to_decription_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
